run_name: 'cifar10'

data:
  data_name: 'cifar10'
  num_clusters_data: 10

training:
  num_epochs: 700
  num_epochs_finetuning: 300
  batch_size: 256
  lr: 0.001
  decay: 0.00001
  decay_kl: 0.005

  inp_shape: 3072
  latent_dim:  [64,64,64,64,64,64] 
  mlp_layers: [512, 512, 512, 512, 512, 512]
  initial_depth: 5
  activation: 'mse' 
  encoder: 'cnn2'
  augment: True
  augmentation_method: 'instancewise_full' 
  aug_decisions_weight: 100
  compute_ll: False

globals:
  wandb_logging: 'disabled'
  eager_mode: False
  seed: 42
  save_model: False
  config_name: 'cifar10'
