run_name: 'omniglot'

data:
  data_name: 'omniglot'
  num_clusters_data: 5
  path: '../../datasets/omniglot'

training:
  num_epochs: 700
  num_epochs_finetuning: 300
  batch_size: 256
  lr: 0.001
  decay: 0.00001
  decay_kl: 0.005

  inp_shape: 784
  latent_dim: [8, 8, 8, 8, 8, 8] 
  mlp_layers: [512, 128, 128, 128, 128, 128] 
  initial_depth: 5
  activation: "sigmoid"
  encoder: 'cnn_omni'
  compute_ll: False
  augment: True
  augmentation_method: 'simple' 
  aug_decisions_weight: 1

globals:
  wandb_logging: 'disabled'
  eager_mode: False
  seed: 42
  save_model: False
  config_name: 'omniglot'
